### ISSUE TITLE
Moderation guide is outdated (Epic/Meta issue)

### ISSUE THREAD

**Issue by NebulaOnion** [matrix-org/matrix.org#1446]
My (own and personal) things I would fix:

- [ ] On Element, Admins and Mods aren't shown by badges, the power level is simply listed right of their username. (This actually confused me at first).
- [ ] All of the images are from the old Element/Riot layout.
- [x] We mention old spec versions, we should link to the latest one. Fixed by #1462 
- [x] #1281 Fixed by #1462 
- [ ] Include an example of removing rooms from a homeserver directory from a HS Admin perspective
- [x] #1017 

I'll try to help what I can with this issue.

**Comment by thibaultamartin** [comment]
Hej, I had missed that issue. FYI we're working on a new version of m.org, and we're writing new docs for it. You can see the new docs for communities as they are being written here: https://github.com/matrix-org/matrix.org/pull/1526

**Comment by thibaultamartin** [comment]
New moderation guide is at https://matrix.org/docs/communities/moderation/

Please feel free to send updates for this guide if you think some things are missing here :)
