### ISSUE TITLE
Meta-issue: implement the "Ecosystem" page

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1543]
- [ ] Ecosystem home page
- [ ] Rework the Clients page #1538 
- [ ] Rework the servers page #1503 
- [ ] Rework the Bots page #1540 
- [ ] Rework the SDKs page
- [ ] Rework the Bridges page #1539 
- [ ] Rework the Hosting page #1541

**Comment by thibaultamartin** [comment]
I like the idea because _in practice_ widgets exist, are used, and there even are companies and products based on widgets… but I'm still a bit reluctant to adding a dedicated section while they're not part of the spec.
