### ISSUE TITLE
Pre-migration checklist

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1724]
- [x] Make sure everything under `.well-known` matches what is currently served. **The risk is to pull the matrix.org homeserver out of the public federation!**
- [x] Make sure old versions of the spec are in their own repo
- [x] Make sure documents in `/legal` are up to date and the links are not breaking
